services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
  redis:
    image: "redis:alpine"
  allinone:
    image: youshandefeiyang/allinone
    container_name: allinone
    privileged: true
    restart: always
    ports:
      - "35455:35455"
    network_mode: bridge
    command: -tv=true -aesKey=zvr2ow75b6mi6uffybmphqj5bpnjlqz5 -userid=31252139 -token=f2f9a7c48db59062c7f28b1c12b0b4bedb1100e1ca7b0e1f9586eba59210e7a4f854e1b5b5d798454c991f739bcd0f485004e30dc8f1647a33dc80e29d8e85702b63cfbe62
